/* ---------------------------------------------------------------------------
   London · Mr & Mrs Kalra · 10 to 13 September 2026
   Single source of truth. The day schedules, master timetable, map and
   directory are all rendered from this file, so editing anything here
   updates every part of the page at once.
--------------------------------------------------------------------------- */

const TRIP = {
  guests: "Mr & Mrs Sunil Kalra",
  occasion: "In celebration of a 27th wedding anniversary",
  dates: "Thursday 10 to Sunday 13 September 2026",
  residence: "The Connaught · Carlos Place, Mayfair",
  preparedBy: "Atin Garg · Concierge Manager",
  total: "£23,339",
};

/* ---------- cost breakdown ------------------------------------------------ */

const COSTS = [
  { key: "accommodation", label: "Accommodation", total: 11391, pct: 48.8, colour: "#D29C33",
    items: [["The Connaught, Grosvenor Suite, three nights, breakfast and Aman Spa included", 11391]] },
  { key: "flights", label: "Flights", total: 8477, pct: 36.3, colour: "#B07C3A",
    items: [["British Airways 256 and Air India 2018, business class, both sectors, two guests", 8477]] },
  { key: "ground", label: "Ground transport", total: 1410, pct: 6.0, colour: "#8C6B4F",
    items: [["First Class Chauffeurs, Friday and Saturday, ten hours each", 900],
            ["First Class Chauffeurs, Heathrow arrival and departure transfers", 260],
            ["Black cabs, eight journeys across the four days", 250]] },
  { key: "dining", label: "Dining", total: 1380, pct: 5.9, colour: "#6B5A4B",
    items: [["Hélène Darroze at The Connaught, three Michelin stars", 800],
            ["Rules, Sunday lunch", 180],
            ["Dishoom Covent Garden, dinner", 140],
            ["Cecconi's Bicester Village, lunch", 140],
            ["The Ivy Royal Windsor, lunch", 120]] },
  { key: "experiences", label: "Experiences", total: 681, pct: 2.9, colour: "#4A4239",
    items: [["Dinner cruise on the Thames, Westminster Pier", 350],
            ["Wine and cheese tasting with London sightseeing", 158],
            ["Tower of London and the Crown Jewels", 74],
            ["Windsor Castle and St George's Chapel", 64],
            ["Bicester Village, Hands Free Shopping", 35]] },
];

/* ---------- the four days -------------------------------------------------
   type      venue | travel | pause
   images    one filename per venue, never repeated
   detail    opens under the row when the guest asks for it
--------------------------------------------------------------------------- */

const DAYS = [
  {
    n: "I", id: "thu", weekday: "Thursday", date: "10 September",
    tag: "Arrival",
    title: "Arrival, and an easy first evening",
    lede: "Nearly ten hours in the air, then a warm, unhurried dinner with no dress code and nothing to prove. The day asks nothing of you.",
    stops: ["The Connaught", "Dishoom Covent Garden"],
    events: [
      { type: "travel", start: "10:05", loc: "Delhi (DEL)", end: "15:20", kind: "Flight", cost: "£8,477",
        title: "Depart Delhi for London",
        line: "British Airways 256, business class, nine hours forty five minutes. Indira Gandhi International to Heathrow Terminal 5." },
      { type: "pause", start: "15:20", loc: "Heathrow (LHR)", end: "16:30", kind: "Arrival",
        title: "Heathrow formalities",
        line: "Immigration and baggage reclaim. Your driver is already waiting, tracking the flight." },
      { type: "travel", start: "16:30", loc: "The Connaught", end: "17:15", kind: "Transfer", cost: "£130",
        title: "Chauffeur into Mayfair",
        line: "First Class Chauffeurs, meet and greet at arrivals, roughly forty five minutes to Carlos Place." },
      { type: "venue", start: "17:15", end: "19:00", kind: "Residence", cost: "£11,391",
        costNote: "three nights",
        title: "Check in · The Connaught, Grosvenor Suite",
        address: "Carlos Place, Mayfair, London W1K 2AL",
        img: "grosvenor-suite",
        alt: "The drawing room of the Grosvenor Suite at The Connaught",
        web: "https://www.maybourne.com/the-connaught/", tel: "+44 20 7499 7070",
        map: "The+Connaught,+Carlos+Place,+Mayfair,+London+W1K+2AL",
        reserved: "Suite held",
        body: "A Maybourne house on Carlos Place holding three Michelin stars and one of the world's most decorated bars under a single roof. The Grosvenor Suite runs to roughly 63 square metres with its own private lobby entrance into a drawing room, interiors by Guy Oliver, and windows over Mount Street and the inner courtyard.",
        detail: [
          ["Included", "Breakfast daily, and access to the Aman Spa"],
          ["Reservations", "+44 20 7107 8843"],
          ["Why here", "Spa access comes with the room, so Friday's couple's ritual is a lift ride away rather than a booking across town."],
        ] },
      { type: "travel", start: "19:00", loc: "Dishoom Covent Garden", end: "19:30", kind: "Travel", cost: "£30",
        title: "Black cab to Covent Garden", line: "About twenty minutes from Carlos Place." },
      { type: "venue", start: "19:30", end: "21:30", kind: "Dining", cost: "£140",
        title: "Dinner at Dishoom Covent Garden",
        address: "12 Upper St. Martin's Lane, London WC2H 9FB",
        img: "dishoom",
        alt: "The dining room at Dishoom Covent Garden",
        web: "https://www.dishoom.com/covent-garden/", tel: "+44 20 7420 9320",
        map: "Dishoom+Covent+Garden,+12+Upper+St+Martin's+Lane,+London+WC2H+9FB",
        reserved: "Table reserved",
        body: "The original Dishoom, set in a restored Bombay Irani café. The house black daal is cooked for more than twenty four hours, and the chicken ruby and the lamb raan are the other signatures. Chosen for the first night because it asks nothing of you: no dress code, no tasting menu, no ceremony, and food that tastes like home at the end of a long flight.",
        detail: [
          ["Hours", "Thursday 08:00 to 23:00"],
          ["Order", "Black daal, chicken ruby, lamb raan, and a house chai to finish"],
        ] },
      { type: "travel", start: "21:30", loc: "The Connaught", end: "22:00", kind: "Travel", cost: "£30",
        title: "Black cab back to the hotel", line: "" },
    ],
  },

  {
    n: "II", id: "fri", weekday: "Friday", date: "11 September",
    tag: "The Anniversary", anniversary: true,
    title: "Shopping, stillness, three stars",
    lede: "Twenty seven years, marked the way it should be. A full retail morning in Oxfordshire, a couple's ritual to reset, then dinner without leaving the building.",
    stops: ["Bicester Village", "Cecconi's", "Aman Spa", "Hélène Darroze"],
    events: [
      { type: "pause", start: "08:00", loc: "The Connaught", end: "08:30", kind: "Breakfast", cost: "Included",
        title: "Breakfast at The Connaught", line: "" },
      { type: "travel", start: "08:30", loc: "Bicester Village", end: "10:00", kind: "Travel", cost: "£450",
        title: "Chauffeur to Oxfordshire",
        line: "First Class Chauffeurs, ten hour hire covering the whole day. Timed to arrive for the 10:00 opening." },
      { type: "venue", start: "10:00", end: "13:30", kind: "Shopping", cost: "£35",
        title: "Bicester Village",
        address: "50 Pingle Drive, Bicester, Oxfordshire OX26 6WD",
        img: "bicester",
        alt: "Boutiques along the street at Bicester Village",
        web: "https://www.thebicestercollection.com/bicester-village/en", tel: "+44 1869 366266",
        map: "Bicester+Village,+50+Pingle+Drive,+Bicester,+Oxfordshire+OX26+6WD",
        reserved: "Personal shopper booked",
        body: "More than 150 boutiques from the luxury houses, an hour and a half from Mayfair. Two things have been arranged in advance to make a long retail morning a comfortable one: one to one personal shopping in the private suites at The Apartment, and Hands Free Shopping, where every boutique packs and holds your purchases centrally so you carry nothing all day.",
        detail: [
          ["Hours", "Friday 09:00 to 21:00"],
          ["Personal shopping", "Booked in the suites at The Apartment, complimentary"],
          ["Hands Free Shopping", "Registered at Guest Concierge on arrival, £35"],
        ] },
      { type: "venue", start: "13:30", end: "14:30", kind: "Dining", cost: "£140",
        title: "Lunch at Cecconi's",
        address: "145 Pingle Drive, Bicester, Oxfordshire OX26 6WD",
        img: "cecconis",
        alt: "The dining room at Cecconi's Bicester Village",
        web: "https://cecconisrestaurants.com/bicester-village/", tel: "+44 1869 366266",
        map: "Cecconi's,+145+Pingle+Drive,+Bicester,+Oxfordshire+OX26+6WD",
        reserved: "Table reserved",
        body: "The first Cecconi's to open outside London, brought to Oxfordshire by Soho House and built to reproduce the Mayfair original: green and white striped tiled floors, marble tables and a round bar. Northern Italian, with handmade pasta, wood fired pizza, cicchetti and seafood. It sits inside the Village, so lunch costs no travel time at all.",
        detail: [
          ["Signatures", "Spaghetti lobster, cacio e pepe, Sicilian prawns"],
          ["Dietary", "Halal options available on request"],
        ] },
      { type: "travel", start: "14:30", loc: "The Connaught", end: "16:00", kind: "Travel",
        title: "Chauffeur back to Mayfair", line: "Same car, same driver, waiting when you finish." },
      { type: "venue", start: "16:30", end: "19:00", kind: "Wellness", cost: "Included",
        costNote: "with the room",
        title: "The couple's ritual at Aman Spa",
        address: "The Connaught, Carlos Place, Mayfair, London W1K 2AL",
        img: "aman-spa",
        alt: "The indoor pool at the Aman Spa, The Connaught",
        web: "https://www.maybourne.com/the-connaught/aman-spa/", tel: "+44 20 3147 7305",
        map: "Aman+Spa+at+The+Connaught,+Carlos+Place,+London+W1K+2AL",
        reserved: "Couple's room held",
        body: "Two and a half hours in the first Aman Spa built outside an Aman resort. The couple's treatment room has two tables behind wooden lattice doors, so this is a shared ritual rather than two appointments running side by side. Five treatment rooms with private dressing areas, a 60 square metre indoor pool, an aromatic steam room and a relaxation lounge.",
        detail: [
          ["Booked", "The Gong Fu Cha Tea Ceremony, ninety minutes, in the couple's room"],
          ["Also available", "The Connaught Body Scrub and Massage, 120 minutes"],
          ["Cost", "Nothing further to pay. Spa access is included in your rate."],
        ] },
      { type: "venue", start: "19:30", end: "21:30", kind: "The anniversary dinner", cost: "£800",
        title: "Hélène Darroze at The Connaught",
        address: "The Connaught, Carlos Place, Mayfair, London W1K 2AL",
        img: "helene-darroze",
        alt: "The dining room at Hélène Darroze at The Connaught",
        web: "https://www.maybourne.com/the-connaught/restaurants-bars/helene-darroze-at-the-connaught/",
        tel: "+44 20 3147 7200",
        map: "Hélène+Darroze+at+The+Connaught,+Carlos+Place,+London+W1K+2AL",
        reserved: "Table reserved",
        highlight: true,
        body: "Three Michelin stars, the highest award the guide gives, in a wood panelled room inside your own hotel. No transfer, no traffic, no coat: you come down from the suite. Darroze cooks modern French built on the produce of south west France, threaded with accents from further afield. Placed here on purpose, straight after the spa, when you are rested rather than newly landed.",
        detail: [
          ["Hours", "Tuesday to Saturday, 18:30 to 21:00"],
          ["Wine", "Pairing selected with the sommelier, included in the cover"],
          ["Dress", "Smart. Jacket preferred, tie not required."],
        ] },
    ],
  },

  {
    n: "III", id: "sat", weekday: "Saturday", date: "12 September",
    tag: "Castle, Wine and River",
    title: "A thousand years of history, then the river",
    lede: "The oldest occupied castle in the world before lunch, English sparkling wine in the late afternoon, and the city lit up from the water after dark.",
    stops: ["Windsor Castle", "The Ivy Royal Windsor", "Wine and cheese tasting", "Dinner cruise"],
    events: [
      { type: "pause", start: "08:30", loc: "The Connaught", end: "09:00", kind: "Breakfast", cost: "Included",
        title: "Breakfast at The Connaught", line: "" },
      { type: "travel", start: "09:00", loc: "Windsor Castle", end: "10:00", kind: "Travel", cost: "£450",
        title: "Chauffeur to Berkshire",
        line: "Roughly 25 miles west on the M4, timed for the 10:00 opening." },
      { type: "venue", start: "10:00", end: "13:30", kind: "Attraction", cost: "£64",
        title: "Windsor Castle and St George's Chapel",
        address: "Windsor, Berkshire SL4 1NJ",
        img: "windsor-castle", img2: "st-georges-chapel",
        alt: "The walls and Round Tower of Windsor Castle",
        alt2: "The nave of St George's Chapel, Windsor Castle",
        web: "https://www.rct.uk/visit/windsor-castle", tel: "+44 303 123 7304",
        map: "Windsor+Castle,+Windsor,+Berkshire+SL4+1NJ",
        reserved: "Tickets held · chapel entry included",
        body: "The oldest and largest occupied castle in the world, a thousand years of continuous royal history, and State Apartments still in official use. Saturday is one of only four days a week St George's Chapel opens to visitors, and the Chapel holds the tombs of ten monarchs including Henry VIII and Charles I, as well as the resting place of Queen Elizabeth II.",
        detail: [
          ["Hours", "Thursday to Monday, 10:00 to 17:15"],
          ["Chapel", "Open to visitors Monday, Thursday, Friday and Saturday, 10:00 to 16:00"],
          ["Why a 10:00 arrival", "It makes three and a half hours comfortable rather than rushed, and it clears the way for lunch at a sensible hour."],
        ] },
      { type: "venue", start: "13:30", end: "15:00", kind: "Dining", cost: "£120",
        title: "Lunch at The Ivy Royal Windsor",
        address: "31 High Street, Royal Windsor, Berkshire SL4 1PQ",
        img: "ivy-windsor",
        alt: "The brasserie room at The Ivy Royal Windsor",
        web: "https://ivycollection.com/restaurants/the-ivy-royal-windsor/", tel: "+44 1753 983555",
        map: "The+Ivy+Royal+Windsor,+31+High+Street,+Windsor+SL4+1PQ",
        reserved: "Table reserved",
        body: "Directly opposite the castle walls on the High Street, in a former hotel behind a red brick facade, so it is a few minutes on foot from the castle exit rather than a drive. An all day menu of British classics and international dishes with a full cocktail and wine list, which means ninety minutes here can be as light or as long as you want after a morning on your feet.",
        detail: [
          ["Hours", "Saturday 09:00 to midnight"],
          ["Access", "Restaurant and bathrooms fully accessible"],
        ] },
      { type: "travel", start: "15:00", loc: "Vauxhall Bridge Road", end: "16:15", kind: "Travel",
        title: "Chauffeur back to London",
        line: "Dropping at Vauxhall Bridge Road for 16:00, half an hour before departure." },
      { type: "venue", start: "16:30", end: "18:00", kind: "Tasting", cost: "£158",
        title: "Wine and cheese tasting, with London sightseeing",
        address: "Departs 258 Vauxhall Bridge Road, London SW1V 1BS",
        img: "wine-tasting",
        alt: "Gusbourne sparkling wine poured alongside a cheese board",
        web: "https://evanevanstours.com/", tel: "+44 20 7932 8385",
        map: "258+Vauxhall+Bridge+Road,+London+SW1V+1BS",
        reserved: "Seats reserved",
        body: "Ninety minutes aboard an air conditioned coach with a live guide, tasting five wines paired with cheese while the route runs past Big Ben, Westminster Abbey, St Paul's, the Tower of London and Tower Bridge. The wine is Gusbourne, a Kent estate commissioned for the coronation wines of King Charles III and Queen Camilla in 2023, poured at the Platinum Jubilee and the 2012 Olympics, and ranked 28th in The World's 50 Best Vineyards 2025. English sparkling wine at the level where it stops being a curiosity.",
        detail: [
          ["The wines", "Brut Reserve 2022, Rosé 2019, Blanc de Blancs 2020, Blanc de Noirs 2020, Oak Reserve 2019"],
          ["Boarding", "Arrive 16:00, thirty minutes before departure"],
          ["The estate", "Gusbourne, Appledore, Kent"],
        ] },
      { type: "travel", start: "18:00", loc: "Westminster Pier", end: "18:30", kind: "Travel", cost: "£30",
        title: "Black cab to Westminster Pier",
        line: "Twenty minutes. There is an hour in hand before boarding, held for a drink near Westminster." },
      { type: "venue", start: "19:30", end: "23:00", kind: "The evening", cost: "£350",
        title: "Dinner cruise on the Thames",
        address: "Westminster Pier, Victoria Embankment, London SW1A 2JH",
        img: "thames-cruise",
        alt: "The Palace of Westminster and Big Ben lit up over the Thames at night",
        web: "https://www.cityexperiences.com/london/city-cruises/", tel: "+44 20 7740 0400",
        map: "Westminster+Pier,+Victoria+Embankment,+London+SW1A+2JH",
        reserved: "Window table for two reserved",
        highlight: true,
        body: "Boarding at 19:30 and sailing at 19:45 from Westminster Pier, directly beneath Big Ben, back alongside at roughly 22:45. A glass of sparkling wine as you board, your own reserved window table for two, dinner across the sailing, a live singer and dancing, a heated saloon and an open upper deck. The whole floodlit sequence of the city passes at close quarters. London does nothing better than this after dark.",
        detail: [
          ["Timing", "Board 19:30, sail 19:45, alongside about 22:45"],
          ["Your table", "Window, for two, reserved by name"],
          ["On boarding", "A welcome glass of sparkling wine"],
        ] },
      { type: "travel", start: "23:00", loc: "The Connaught", end: "23:30", kind: "Travel", cost: "£40",
        title: "Black cab back to the hotel", line: "" },
    ],
  },

  {
    n: "IV", id: "sun", weekday: "Sunday", date: "13 September",
    tag: "Departure",
    title: "Crown jewels, and a long lunch",
    lede: "An early start at the Tower while it is still quiet, then the oldest restaurant in London for an unhurried final meal, and a clean departure at four.",
    stops: ["Tower of London", "Rules", "Burlington Arcade"],
    events: [
      { type: "pause", start: "08:00", loc: "The Connaught", end: "08:30", kind: "Breakfast", cost: "Included",
        title: "Breakfast at The Connaught", line: "" },
      { type: "travel", start: "08:30", loc: "Tower of London", end: "09:00", kind: "Travel", cost: "£30",
        title: "Black cab to the Tower", line: "Timed for the 09:00 opening." },
      { type: "venue", start: "09:00", end: "12:00", kind: "Attraction", cost: "£74",
        title: "Tower of London and the Crown Jewels",
        address: "Tower of London, London EC3N 4AB",
        img: "tower-of-london", img2: "crown-jewels",
        alt: "The Tower of London seen from the River Thames",
        alt2: "The Imperial State Crown, part of the Crown Jewels",
        web: "https://www.hrp.org.uk/tower-of-london/", tel: "+44 333 320 6000",
        map: "Tower+of+London,+London+EC3N+4AB",
        reserved: "Tickets held · Yeoman Warder tour included",
        body: "Nearly a thousand years of fortress, palace and prison, and the working home of the Crown Jewels. Arriving for the 09:00 opening is the whole trick: it gives you a clean run at the Jewel House before the day builds. The Yeoman Warder guided tour is included in your admission and is the best hour on the site.",
        detail: [
          ["Hours", "Daily 09:00 to 17:30, last entry 16:30"],
          ["Luggage", "There is no storage on site. Everything stays with The Connaught until the 16:00 car."],
        ] },
      { type: "travel", start: "12:00", loc: "Rules", end: "12:30", kind: "Travel", cost: "£30",
        title: "Black cab to Covent Garden", line: "" },
      { type: "venue", start: "12:30", end: "14:00", kind: "Dining", cost: "£180",
        title: "Lunch at Rules",
        address: "35 Maiden Lane, Covent Garden, London WC2E 7LB",
        img: "rules",
        alt: "The frontage of Rules restaurant on Maiden Lane, Covent Garden",
        web: "https://rules.co.uk/", tel: "+44 20 7836 5314",
        map: "Rules+Restaurant,+35+Maiden+Lane,+London+WC2E+7LB",
        reserved: "Table reserved",
        body: "Established in 1798 by Thomas Rule, the oldest restaurant in London, running continuously through the reigns of ten monarchs under only four family owners. It specialises in classic British game, much of it from the restaurant's own estate in the High Pennines. The timing is a genuine piece of luck: mid September falls inside the game season, so grouse, partridge and venison should all be on the card.",
        detail: [
          ["Hours", "Sunday from 12:00"],
          ["Dress", "Smart dress preferred. No shorts or sportswear. Jacket and tie not required."],
          ["In season", "Grouse, partridge and venison from the restaurant's own estate"],
        ] },
      { type: "travel", start: "14:00", loc: "Burlington Arcade", end: "14:30", kind: "Travel", cost: "£30",
        title: "Black cab to Piccadilly", line: "" },
      { type: "venue", start: "14:30", end: "15:45", kind: "Shopping",
        title: "Burlington Arcade and Piccadilly",
        address: "51 Piccadilly, London W1J 0QJ",
        img: "burlington-arcade",
        alt: "Looking down the length of Burlington Arcade",
        web: "https://burlingtonarcade.com/", tel: "",
        map: "Burlington+Arcade,+51+Piccadilly,+London+W1J+0QJ",
        body: "Britain's longest covered shopping arcade, opened in 1819 and still patrolled by its own Beadles, the oldest small police force in the world, in top hats and frock coats. Ten minutes from Rules and on the way back to Mayfair, and one of very few genuinely elegant places to shop in London on a Sunday afternoon.",
        detail: [
          ["Hours", "Sunday 11:00 to 18:00"],
          ["Nearby", "Bond Street and Piccadilly, both a short walk"],
          ["Note", "No central telephone line is published. Boutiques are listed individually on the arcade's own site."],
        ] },
      { type: "travel", start: "15:45", loc: "The Connaught", end: "16:00", kind: "Travel", cost: "£30",
        title: "Black cab back to the hotel", line: "" },
      { type: "pause", start: "16:00", loc: "The Connaught", end: "16:30", kind: "Checkout",
        title: "Checkout and hotel formalities",
        line: "Luggage has been held since this morning and will be brought down to the car." },
      { type: "travel", start: "16:30", loc: "LHR Terminal 2", end: "17:30", kind: "Transfer", cost: "£130",
        title: "Chauffeur to Heathrow Terminal 2",
        line: "Sunday evening traffic is lighter than a weekday, so this is a comfortable margin." },
      { type: "pause", start: "17:30", loc: "LHR Terminal 2", end: "20:35", kind: "Departure",
        title: "Airport formalities", line: "" },
      { type: "travel", start: "20:35", loc: "LHR Terminal 2", end: "11:00", kind: "Flight", endNote: "+1",
        title: "London to Delhi",
        line: "Air India 2018, business class, Boeing 787-9, nine hours fifty five minutes. Landing at 11:00 the following morning." },
    ],
  },
];

/* ---------- map ----------------------------------------------------------- */

const PINS = [
  { day: "all", name: "The Connaught", sub: "Your residence", lat: 51.5099, lng: -0.1490, home: true },
  { day: "thu", name: "Dishoom Covent Garden", sub: "Thursday, dinner", lat: 51.5115, lng: -0.1275 },
  { day: "fri", name: "Bicester Village", sub: "Friday, shopping", lat: 51.8865, lng: -1.1560 },
  { day: "fri", name: "Cecconi's Bicester Village", sub: "Friday, lunch", lat: 51.8869, lng: -1.1548 },
  { day: "fri", name: "Aman Spa", sub: "Friday, the couple's ritual", lat: 51.5099, lng: -0.1492 },
  { day: "fri", name: "Hélène Darroze", sub: "Friday, the anniversary dinner", lat: 51.5100, lng: -0.1488 },
  { day: "sat", name: "Windsor Castle", sub: "Saturday, morning", lat: 51.4839, lng: -0.6044 },
  { day: "sat", name: "The Ivy Royal Windsor", sub: "Saturday, lunch", lat: 51.4835, lng: -0.6081 },
  { day: "sat", name: "Wine and cheese tasting", sub: "Saturday, departs Vauxhall Bridge Road", lat: 51.4906, lng: -0.1373 },
  { day: "sat", name: "Westminster Pier", sub: "Saturday, the dinner cruise", lat: 51.5010, lng: -0.1236 },
  { day: "sun", name: "Tower of London", sub: "Sunday, from opening", lat: 51.5081, lng: -0.0759 },
  { day: "sun", name: "Rules", sub: "Sunday, lunch", lat: 51.5108, lng: -0.1235 },
  { day: "sun", name: "Burlington Arcade", sub: "Sunday, afternoon", lat: 51.5089, lng: -0.1400 },
];

/* ---------- directory ----------------------------------------------------- */

const DIRECTORY = [
  { group: "Residence and wellness", rows: [
    ["The Connaught", "maybourne.com", "https://www.maybourne.com/the-connaught/", "+44 20 7499 7070", "Carlos Place, Mayfair W1K 2AL"],
    ["Aman Spa at The Connaught", "maybourne.com", "https://www.maybourne.com/the-connaught/aman-spa/", "+44 20 3147 7305", "The Connaught, couple's treatment room"],
  ]},
  { group: "Dining", rows: [
    ["Hélène Darroze at The Connaught", "maybourne.com", "https://www.maybourne.com/the-connaught/restaurants-bars/helene-darroze-at-the-connaught/", "+44 20 3147 7200", "Carlos Place W1K 2AL · Tuesday to Saturday, 18:30 to 21:00"],
    ["Dishoom Covent Garden", "dishoom.com", "https://www.dishoom.com/covent-garden/", "+44 20 7420 9320", "12 Upper St. Martin's Lane WC2H 9FB · Thursday 08:00 to 23:00"],
    ["Cecconi's Bicester Village", "cecconisrestaurants.com", "https://cecconisrestaurants.com/bicester-village/", "+44 1869 366266", "145 Pingle Drive, Bicester OX26 6WD"],
    ["The Ivy Royal Windsor", "ivycollection.com", "https://ivycollection.com/restaurants/the-ivy-royal-windsor/", "+44 1753 983555", "31 High Street, Windsor SL4 1PQ · Saturday 09:00 to 00:00"],
    ["Rules", "rules.co.uk", "https://rules.co.uk/", "+44 20 7836 5314", "35 Maiden Lane WC2E 7LB · Sunday from 12:00"],
  ]},
  { group: "Experiences and attractions", rows: [
    ["Windsor Castle", "rct.uk", "https://www.rct.uk/visit/windsor-castle", "+44 303 123 7304", "Windsor, Berkshire · Thursday to Monday, 10:00 to 17:15"],
    ["St George's Chapel", "stgeorges-windsor.org", "https://www.stgeorges-windsor.org/", "See Windsor Castle", "Monday, Thursday, Friday, Saturday, 10:00 to 16:00"],
    ["Tower of London", "hrp.org.uk", "https://www.hrp.org.uk/tower-of-london/", "+44 333 320 6000", "London EC3N 4AB · daily 09:00 to 17:30, last entry 16:30"],
    ["Evan Evans Tours", "evanevanstours.com", "https://evanevanstours.com/", "+44 20 7932 8385", "258 Vauxhall Bridge Road SW1V 1BS · departs 16:30"],
    ["City Cruises, dinner cruise", "cityexperiences.com", "https://www.cityexperiences.com/london/city-cruises/", "+44 20 7740 0400", "Westminster Pier, Victoria Embankment SW1A 2JH · board 19:30"],
  ]},
  { group: "Shopping", rows: [
    ["Bicester Village", "thebicestercollection.com", "https://www.thebicestercollection.com/bicester-village/en", "+44 1869 366266", "50 Pingle Drive, Bicester OX26 6WD · Friday 09:00 to 21:00"],
    ["Burlington Arcade", "burlingtonarcade.com", "https://burlingtonarcade.com/", "No central line published", "51 Piccadilly W1J 0QJ · Sunday 11:00 to 18:00"],
    ["Bond Street", "bondstreet.co.uk", "https://www.bondstreet.co.uk/", "No central line published", "New and Old Bond Street, Mayfair W1S"],
  ]},
  { group: "Transport", rows: [
    ["First Class Chauffeurs", "fcchauffeurs.co.uk", "https://www.fcchauffeurs.co.uk/", "+44 20 7101 3322", "31 Kensington Church Street W8 4LL"],
    ["Addison Lee Executive", "addisonlee.com", "https://www.addisonlee.com/", "+44 20 7387 8888", "24 hours · flight tracking · thirty minutes inclusive waiting"],
    ["British Airways", "britishairways.com", "https://www.britishairways.com/", "+44 800 123 5100", "BA 256 · Delhi to Heathrow Terminal 5 · 10 September"],
    ["Air India", "airindia.com", "https://www.airindia.com/", "Via your concierge", "AI 2018 · Heathrow Terminal 2 to Delhi · 13 September"],
  ]},
];
